[package]
name = "rust-sse-sample"
version = "0.1.0"
edition = "2024"

[dependencies]
uuid = { version = "1.19.0", features = ["v7"] }
actix-web = "4"
serde = "1.0.228"
async-trait = "0.1.89"
tokio = "1.49.0"
